kind: Deployment
apiVersion: apps/v1
metadata:
  name: gradio-rag-milvus-vllm-openai
  labels:
    app: gradio-rag-milvus-vllm-openai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gradio-rag-milvus-vllm-openai
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gradio-rag-milvus-vllm-openai
    spec:
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      restartPolicy: Always
      schedulerName: default-scheduler
      affinity: {}
      terminationGracePeriodSeconds: 120
      securityContext: {}
      containers:
        - resources:
            limits:
              cpu: '2'
              memory: 4Gi
              nvidia.com/gpu: '1'
            requests:
              cpu: '1'
              memory: 2Gi
              nvidia.com/gpu: '1'
          readinessProbe:
            httpGet:
              path: /queue/status
              port: http
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: server
          livenessProbe:
            httpGet:
              path: /queue/status
              port: http
              scheme: HTTP
            timeoutSeconds: 8
            periodSeconds: 100
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: APP_TITLE
              value: 'Red Hat Documentation Chatbot (English)'
            - name: SHOW_TITLE_IMAGE
              value: 'True'
            - name: INFERENCE_SERVER_URL
              value: 'https://qwen-25-7b-instruct-peter-lm.apps.rosa.peter-rosa-hcp.y0r0.p3.openshiftapps.com/v1'
            - name: MODEL_NAME
              value: 'qwen-25-7b-instruct'
            - name: MAX_TOKENS
              value: '1024'
            - name: TOP_P
              value: '0.95'
            - name: TEMPERATURE
              value: '0.01'
            - name: PRESENCE_PENALTY
              value: '1.03'
            - name: MILVUS_HOST
              value: 'vectordb-milvus.milvus.svc.cluster.local'
            - name: MILVUS_PORT
              value: '19530'
            - name: MILVUS_USERNAME
              value: 'root'
            - name: MILVUS_PASSWORD
              value: 'Milvus'
            - name: MILVUS_COLLECTIONS_FILE
              value: '/opt/app-root/src/collections.json'
            - name: DEFAULT_COLLECTION
              value: 'none'
            - name: PROMPT_FILE
              value: 'prompt.txt'
            - name: MAX_RETRIEVED_DOCS
              value: '4'
            - name: SCORE_THRESHOLD
              value: '0.99'
            - name: EMBEDDING_MODEL_NAME
              value: 'ibm-granite/granite-embedding-278m-multilingual'
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          ports:
            - name: http
              containerPort: 7860
              protocol: TCP
          imagePullPolicy: IfNotPresent
          startupProbe:
            httpGet:
              path: /queue/status
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 24
          terminationMessagePolicy: File
          image: 'quay.io/nebula0248/openshift-ai-llm-gradio-rag-milvus-vllm-openai:main'
          volumeMounts:
            - name: collections
              mountPath: /opt/app-root/src/collections.json
              subPath: collections.json
            - name: prompt
              mountPath: /opt/app-root/src/prompt.txt
              subPath: prompt.txt
      volumes:
        - name: collections
          configMap:
            name: collections
            items:
              - key: collections.json
                path: collections.json
            defaultMode: 420
        - name: prompt
          configMap:
            name: prompt
            items:
              - key: prompt.txt
                path: prompt.txt
            defaultMode: 420
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
